/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardBranchesIndexRouteImport } from './routes/_dashboard.branches.index'
import { Route as DashboardBranchesNameRouteImport } from './routes/_dashboard.branches.$name'
import { Route as DashboardGroupsIdRouteImport } from './routes/_dashboard.groups.$id'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesIndexRoute = DashboardBranchesIndexRouteImport.update({
  id: '/branches/',
  path: '/branches/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchesNameRoute = DashboardBranchesNameRouteImport.update({
  id: '/branches/$name',
  path: '/branches/$name',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsIdRoute = DashboardGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/branches/$name': typeof DashboardBranchesNameRoute
  '/groups/$id': typeof DashboardGroupsIdRoute
  '/branches/': typeof DashboardBranchesIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/branches/$name': typeof DashboardBranchesNameRoute
  '/groups/$id': typeof DashboardGroupsIdRoute
  '/branches': typeof DashboardBranchesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/branches/$name': typeof DashboardBranchesNameRoute
  '/_dashboard/groups/$id': typeof DashboardGroupsIdRoute
  '/_dashboard/branches/': typeof DashboardBranchesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$' | '/' | '/branches/$name' | '/groups/$id' | '/branches/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/' | '/branches/$name' | '/groups/$id' | '/branches'
  id:
    | '__root__'
    | '/$'
    | '/_dashboard'
    | '/_dashboard/'
    | '/_dashboard/branches/$name'
    | '/_dashboard/groups/$id'
    | '/_dashboard/branches/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/branches/': {
      id: '/_dashboard/branches/'
      path: '/branches'
      fullPath: '/branches/'
      preLoaderRoute: typeof DashboardBranchesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/branches/$name': {
      id: '/_dashboard/branches/$name'
      path: '/branches/$name'
      fullPath: '/branches/$name'
      preLoaderRoute: typeof DashboardBranchesNameRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/groups/$id': {
      id: '/_dashboard/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof DashboardGroupsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBranchesNameRoute: typeof DashboardBranchesNameRoute
  DashboardGroupsIdRoute: typeof DashboardGroupsIdRoute
  DashboardBranchesIndexRoute: typeof DashboardBranchesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBranchesNameRoute: DashboardBranchesNameRoute,
  DashboardGroupsIdRoute: DashboardGroupsIdRoute,
  DashboardBranchesIndexRoute: DashboardBranchesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
